-- Could not auto-generate a down migration
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.products DROP COLUMN IF EXISTS category_id;
-- ALTER TABLE public.products ADD category_id uuid NOT NULL;
-- ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_product_category_fkey;
