-- Could not auto-generate a down migration
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.todos ALTER COLUMN id SET DEFAULT gen_random_uuid();
-- ALTER TABLE public.todos ALTER COLUMN created SET DEFAULT now();
-- ALTER TABLE public.todos ALTER COLUMN updated SET DEFAULT now();
-- ALTER TABLE public.todos ALTER COLUMN id SET DEFAULT gen_random_uuid();
-- ALTER TABLE public.todos ALTER COLUMN created SET DEFAULT now();
-- ALTER TABLE public.todos ALTER COLUMN updated SET DEFAULT now();
